import { useEffect } from "react";

// useEffect(() => {
//     async function fetchData() {
//       const response = await fetch(
//         "https://react-api-4721a-default-rtdb.firebaseio.com/items.json",
//         {
//           method: "PUT",
//           body: JSON.stringify(items),
//         }
//       );
//     }
//     fetchData();
//   }, []);

const items = [
  {
    id: "R-94",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван кожаный “R-94”",
    titleFull: "Диван кожаный “R-94”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "5,0",
    imgPrimary: "src/assets/R-94-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 94990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "T-75",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван апартековый “T-75”",
    titleFull: "Диван апартековый “T-75”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,9",
    imgPrimary: "src/assets/T-75-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 69990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "D-31",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван тканевый “D-31”",
    titleFull: "Диван тканевый прямой “D-31”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,8",
    imgPrimary: "src/assets/D-31-1.png",
    img2: "src/assets/D-31-2.png",
    img3: "src/assets/D-31-3.png",
    img4: "src/assets/D-31-4.png",
    imgSchematic1: "src/assets/D-31-s-1.png",
    imgSchematic2: "src/assets/D-31-s-1.png",
    price: 28490,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "Y-68",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван велюровый “Y-68”",
    titleFull: "Диван велюровый “Y-68”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,8",
    imgPrimary: "src/assets/Y-68-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 22990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "W-95",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван из шинила “W-95”",
    titleFull: "Диван из шинила “W-95”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,8",
    imgPrimary: "src/assets/W-95-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 22990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "G-41",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван флоковый “G-41”",
    titleFull: "Диван флоковый “G-41”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,8",
    imgPrimary: "src/assets/G-41-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 17990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "V-43",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван шиниловый “V-43”",
    titleFull: "Диван шиниловый “V-43”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,8",
    imgPrimary: "src/assets/V-43-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 19990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "S-99",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван велюровый “S-99”",
    titleFull: "Диван велюровый “S-99”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,7",
    imgPrimary: "src/assets/S-99-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 19990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "F-85",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван из кожзама “F-85”",
    titleFull: "Диван из кожзама “F-85”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,7",
    imgPrimary: "src/assets/F-85-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 26990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "H-64",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван флоковый “H-64”",
    titleFull: "Диван флоковый “H-64”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,6",
    imgPrimary: "src/assets/H-64-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 25990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "H-58",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван флоковый “H-58”",
    titleFull: "Диван флоковый “H-58”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,6",
    imgPrimary: "src/assets/H-58-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 23990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "R-43",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван из кожзама “R-43”",
    titleFull: "Диван из кожзама “R-43”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,6",
    imgPrimary: "src/assets/R-43-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 33990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "С-42",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван из шинила “С-42”",
    titleFull: "Диван из шинила “С-42”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,6",
    imgPrimary: "src/assets/С-42-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 18990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "U-58",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван велюровый “U-58”",
    titleFull: "Диван велюровый “U-58”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,6",
    imgPrimary: "src/assets/U-58-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 21990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "F-41",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван флоковый “F-41”",
    titleFull: "Диван флоковый “F-41”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,5",
    imgPrimary: "src/assets/F-41-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 17990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "R-85",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван велюровый “R-85”",
    titleFull: "Диван велюровый “R-85”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,5",
    imgPrimary: "src/assets/R-85-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 34990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "S-44",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван велюровый “S-44”",
    titleFull: "Диван велюровый “S-44”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,5",
    imgPrimary: "src/assets/S-44-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 19990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
  {
    id: "С-80",
    categoryFull: "Прямые тканевые диваны",
    category: "Диваны",
    subCategory: "Прямые диваны",
    titleShort: "Диван из шинила “С-80”",
    titleFull: "Диван из шинила “С-80”",
    descriptionShort: "Мини 120 см без ящика Stark синий (Рогожка)",
    rating: "4,4",
    imgPrimary: "src/assets/С-80-1.png",
    img2: "src/assets/empty-img.png",
    img3: "src/assets/empty-img.png",
    img4: "src/assets/empty-img.png",
    imgSchematic1: "src/assets/empty-img.png",
    imgSchematic2: "src/assets/empty-img.png",
    price: 20990,
    descriptionTitle: "Опорный механизм",
    descriptionFull:
      "Опорный механизм напоминает пантограф, к которому добавили дополнительную секцию. У опорного дивана сиденье «выпрыгивает» вперёд и вытаскивает вторую часть спального места. Заключительный штрих — опустить спинку.\n" +
      "Этот механизм не портит пол и не боится ковров. Требуется чуть больше силы, чтобы разложить диван, но подросток справится.",
    warranty: 18,
    vendorCode: "AAA41269004",
    length: 163,
    height: 90,
    width: 108,
    SleepingArea: "200 см х 125 см",
    landingHeight: 45,
    mechanism: "Опорный",
    upholstery: "Рогожка",
    color: "Синий",
    filler: "Независимый пружинный блок",
    frame: "Металл. рама с дерев. латами",
    seats: "Двухместные",
    return: "Условия",
  },
];

const special = [
  {
    id: "i1",
    title: "Кресло велюровое “X-24”",
    img: "src/assets/special-1.png",
    secondImg: "",
    price: 24990,
    discount: 9000,
    sizeIsBig: false,
  },
  {
    id: "i2",
    title: "Диван тканевый “Z-44”",
    img: "src/assets/special-2.png",
    secondImg: "src/assets/special-2-2.png",
    price: 32990,
    discount: 10000,
    sizeIsBig: true,
  },
  {
    id: "i3",
    title: "Будильник  “Quartz-23”",
    img: "src/assets/special-3.png",
    secondImg: "",
    price: 1290,
    discount: 600,
    sizeIsBig: false,
  },
  {
    id: "i4",
    title: "Мини-скульптура “Oh my deer”",
    img: "src/assets/special-4.png",
    secondImg: "",
    price: 990,
    discount: 300,
    sizeIsBig: false,
  },
  {
    id: "i5",
    title: "Диван вел-флок “Z-85”",
    img: "src/assets/special-5.png",
    secondImg: "src/assets/special-2-2.png",
    price: 32990,
    discount: 10000,
    sizeIsBig: true,
  },
  {
    id: "i6",
    title: "Термометр + гидрометр “H-18”",
    img: "src/assets/special-6.png",
    secondImg: "",
    price: 2090,
    discount: 700,
    sizeIsBig: false,
  },
];
